<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -Fusource;source/base;../../packager/units/%(CPU_TARGET)-%(OS_TARGET);../lazutils/lib/%(CPU_TARGET)-%(OS_TARGET);../../lcl/units/%(CPU_TARGET)-%(OS_TARGET);../../lcl/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../lazcontrols/lib/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../ideintf/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);. -Fisource;source/base  -MObjFPC -Sgi -O1 -g -gl -vei -l pl_indycomp.pas"/>
</CONFIG>
